MAESTRO_PATH: "datasets/maestros/base_maestro.txt"
# Validation
VALIDATION_CSV_PATH: "datasets/validation/validation.csv"
VALIDATION_TXT_QUERY_COLUMNS_STRUCT: [['s_PROVINCIA'], ['s_PARTIDO'], ['s_LOCALIDAD'], [],['s_NOM_CALLE_ABR']]

# Searcher
COLUMNS_TO_RETURN: ['CPA', 'PROVINCIA', 'PARTIDO', 'LOCALIDAD', 'localidad_original', 'MUNICIPIO', 'NOM_CALLE_ABR', 'LATITUD', 'LONGITUD', 'HEIGHT', 'COD_DESDE', 'COD_HASTA'] 
MAX_ADDRESSES_TO_SHOW: 5
MAX_ADDRESSES_TO_OPERATE: 25

# Structured address searcher
SEARCHER_CONFIG: [
  {
    "MODEL_PATH": "models/training/provincia/provincia-abreviaciones_20250701_164948/copies/checkpoint-12260", 
    "QUERY_COLUMNS": ['PROVINCIA'],
    "MAX_ADDRESSES_TO_SHOW": 1,
    "MAX_ADDRESSES_TO_OPERATE": 1,
    "THRESHOLD_ABS": 0.3,
    "THRESHOLD_REL": 0.05,
    "HAS_HEIGHT": False,
    "SAVE_EMBEDDINGS_PATH": "embeddings/provincia_embedded.npy",
    "LOAD_EMBEDDINGS_PATH": "embeddings/provincia_embedded.npy"
  },
  {
    "MODEL_PATH": "models/training/municipio_partido_localidad/logs_completos-municipio_partido_localidad_20250614_071606/copies/checkpoint-38800",
    "QUERY_COLUMNS": ['PARTIDO', 'LOCALIDAD', 'MUNICIPIO'],
    "MAX_ADDRESSES_TO_SHOW": 1,
    "MAX_ADDRESSES_TO_OPERATE": 1,
    "THRESHOLD_ABS": 0.3,
    "THRESHOLD_REL": 0.05,
    "HAS_HEIGHT": False,
    "SAVE_EMBEDDINGS_PATH": "embeddings/municipio_partido_localidad_embedded.npy",
    "LOAD_EMBEDDINGS_PATH": "embeddings/municipio_partido_localidad_embedded.npy"
  },
  {
    "MODEL_PATH": "models/training/street/logs_completos-street_20250620_110757/copies/checkpoint-3300",
    "QUERY_COLUMNS": ['NOM_CALLE_ABR'],
    "MAX_ADDRESSES_TO_SHOW": 5,
    "MAX_ADDRESSES_TO_OPERATE": 25,
    "THRESHOLD_ABS": 0.3,
    "THRESHOLD_REL": 0.05,
    "HAS_HEIGHT": True,
    "SAVE_EMBEDDINGS_PATH": "embeddings/street_embedded.npy",
    "LOAD_EMBEDDINGS_PATH": "embeddings/street_embedded.npy"
  }
]

# Embeddings settings
EMBEDDINGS_BATCH_SIZE: 512
SAVE_EMBEDDINGS: True
LOAD_EMBEDDINGS: False

# GPU settings
USE_GPU: False

# Logging settings
SAVE_LOGS: False
LOGS_FILE_PATH: "logs/base_maestro_sample.log"

# Localidades linderas
APPLY_LOCALIDADES_LINDERAS: False
LOCALIDADES_LINDERAS_PATH: "datasets/localidades_linderas/Loc_Linderas_depurado_cant_lineas.xlsx"
LOCALIDADES_COUMNS: ['LOCALIDAD_1','LOCALIDAD_']