# Searcher
COLUMNS_TO_RETURN: ['CPA', 'PROVINCIA', 'PARTIDO', 'LOCALIDAD', 'localidad_original', 'MUNICIPIO', 'NOM_CALLE_ABR', 'LATITUD', 'LONGITUD', 'HEIGHT', 'COD_DESDE', 'COD_HASTA']

# Structured address searcher
SEARCHER_CONFIG: [
  {
    "MODEL_PATH": "models/prod/unstructured/embeddings_model_1", 
    "QUERY_COLUMNS": ['PROVINCIA', 'PARTIDO', 'LOCALIDAD', 'MUNICIPIO', 'NOM_CALLE_ABR'],
    "MAX_ADDRESSES_TO_SHOW": 5,
    "MAX_ADDRESSES_TO_OPERATE": 100,
    "THRESHOLD_ABS": 0.3,
    "THRESHOLD_REL": 0.05,
    "HAS_HEIGHT": True,
    "SAVE_EMBEDDINGS_PATH": "embeddings/unstructured_embedded.npy",
    "LOAD_EMBEDDINGS_PATH": "embeddings/unstructured_embedded.npy"
  }
]

# Maestro settings
MAESTRO_PROCESSED_PATH: "datasets/maestros/maestro_unstruct_processed.csv"

# Embeddings settings
EMBEDDINGS_BATCH_SIZE: 512
SAVE_EMBEDDINGS: True
LOAD_EMBEDDINGS: False

# GPU settings
USE_GPU: False

# Logging settings
SAVE_LOGS: False
LOGS_FILE_PATH: "logs/base_maestro_sample.log"

# Localidades linderas
APPLY_LOCALIDADES_LINDERAS: True
LOCALIDADES_LINDERAS_PATH: "datasets/localidades_linderas/Loc_Linderas_depurado_cant_lineas.xlsx"
LOCALIDADES_COUMNS: ['LOCALIDAD_1','LOCALIDAD_']